config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :brands
  resources :transactions
  resources :customers
  resources :products

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
<nav class="top-bar">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "Toy City", '/' %></a></h1>
    </li>
  </ul>
  <section class="top-bar-section">
    <ul class="right">
      <li class="divider"></li>
      <li><%= link_to "Products", products_path %></li>
      <li class="divider"></li>
      <li><%= link_to "Brands", brands_path %></li>
      <li class="divider"></li>
      <li><%= link_to "Transactions", transactions_path %></li>
      <li class="divider"></li>
      <li><%= link_to "Customers", customers_path %></li>
    </ul>
  </section>
</nav>
<div class="row">
  <div class="small-12 columns">
    <div class="contain">
      <%= yield %>
    </div>
  </div>
</div>
<!--
<div class="row">
  <div class="small-12 columns"><%= yield %></div>
  <% if current_page?(root_path) %>
  <div class="small-4 columns">
    <h2 class="subheader">About Toy City</h2>
    Founded in 1986, Toy City is the best toy store in the world!
    <p>We sell real toys, not that plastic crap that you can buy off ebay.</p>
    <ul style="list-style:none;">
      <li>123 Main St.</li>
      <li>New York, NY</li>
      <li>(555) 279-9722</li>
    </ul>
  </div>
  <% end %>
</div>
    <%= javascript_include_tag "application" %>
  </body>
</html> -->